# Generated by Django 2.1.7 on 2019-04-21 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
       
    ]
