# Generated by Django 2.1.7 on 2019-04-21 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190421_2307'),
    ]

    operations = [
        
    ]
