# Generated by Django 2.1.7 on 2019-04-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190422_1808'),
    ]

