# Generated by Django 2.1.7 on 2019-04-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20190422_1824'),
    ]

    
