# Generated by Django 2.1.7 on 2019-04-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20190422_1830'),
    ]

    operations = [
        
    ]
