# Generated by Django 2.1.7 on 2019-04-22 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_remove_album_artist'),
    ]

    operations = [
        
        
    ]
