# Generated by Django 2.1.7 on 2019-04-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_remove_album_album_id'),
    ]

    operations = [
        
        
    ]
