# Generated by Django 2.1.7 on 2019-04-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20190422_1914'),
    ]

    operations = [
        
    ]
