# Generated by Django 2.1.7 on 2019-04-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20190422_1923'),
    ]

   
